# Generated by Django 5.1.11 on 2025-06-25 13:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('asset_type', models.IntegerField(choices=[(0, 'Other'), (1, 'Cidr'), (2, 'Url'), (3, 'Executable'), (4, 'Apple Store App Id'), (5, 'Testflight'), (6, 'Other Ipa'), (7, 'Google Play App Id'), (8, 'Other Apk'), (9, 'Windows App Store App Id'), (10, 'Source Code'), (11, 'Downloadable Executables'), (12, 'Hardware')], default=0)),
                ('asset_identifier', models.CharField(blank=True, max_length=512)),
                ('instruction', models.TextField(blank=True)),
                ('max_severity', models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=0)),
                ('eligible_for_bounty', models.BooleanField(default=False)),
                ('eligible_for_submission', models.BooleanField(default=False)),
                ('confidentiality_requirement', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High')], null=True)),
                ('integrity_requirement', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High')], null=True)),
                ('availability_requirement', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High')], null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, 1))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, 1))),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('handle', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('codename', models.CharField(blank=True, max_length=512)),
                ('name', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512)),
                ('state', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(null=True)),
                ('vulnerability_information', models.TextField(blank=True)),
                ('triaged_at', models.DateTimeField(null=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('last_reporter_activity_at', models.DateTimeField(null=True)),
                ('first_program_activity_at', models.DateTimeField(null=True)),
                ('last_program_activity_at', models.DateTimeField(null=True)),
                ('bounty_awarded_at', models.DateTimeField(null=True)),
                ('swag_awarded_at', models.DateTimeField(null=True)),
                ('disclosed_at', models.DateTimeField(null=True)),
                ('reporter_agreed_on_going_public_at', models.DateTimeField(null=True)),
                ('last_public_activity_at', models.DateTimeField(null=True)),
                ('last_activity_at', models.DateTimeField(null=True)),
                ('weakness', models.CharField(blank=True, max_length=512)),
                ('sub_weakness', models.CharField(blank=True, max_length=512)),
                ('synack_state', models.IntegerField(choices=[(0, 'Other'), (1, 'Accepted'), (2, 'In Queue'), (3, 'Rejected')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=512)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('awarded_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('awarded_bonus_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('awarded_currency', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, 1))),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbprograms.report')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('handle', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=512)),
                ('currency', models.CharField(blank=True, max_length=512)),
                ('submission_state', models.IntegerField(choices=[(0, 'Other'), (1, 'Open'), (2, 'Api Only'), (3, 'Paused')], default=0)),
                ('triage_active', models.BooleanField(default=False)),
                ('state', models.IntegerField(choices=[(0, 'Other'), (1, 'Sandboxed'), (2, 'Soft Launched'), (3, 'Public Mode')], default=0)),
                ('started_accepting_at', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, 1))),
                ('number_of_reports_for_user', models.IntegerField(default=0)),
                ('number_of_valid_reports_for_user', models.IntegerField(default=0)),
                ('bounty_earned_for_user', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_invitation_accepted_at_for_user', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, 1))),
                ('allows_bounty_splitting', models.BooleanField(default=False)),
                ('offers_bounties', models.BooleanField(default=False)),
                ('add_to_scope', models.BooleanField(default=True)),
                ('synack_category', models.IntegerField(choices=[(0, 'Other'), (1, 'Web Application'), (2, 'Host')], default=0)),
                ('synack_collaboration', models.IntegerField(choices=[(0, 'Other'), (1, 'FVEY'), (2, 'USA')], default=0)),
                ('synack_missions_only', models.BooleanField(default=False)),
                ('synack_dypri', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbprograms.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ScopeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.IntegerField(choices=[(0, 'Derived'), (1, 'Custom')], default=1)),
                ('rule_context', models.IntegerField(choices=[(0, 'Always'), (1, 'Cnames'), (2, 'Securitytrails'), (3, 'Amass'), (4, 'Amassbf'), (5, 'Buckets')], default=0)),
                ('in_scope', models.BooleanField(default=False)),
                ('host', models.CharField(blank=True, max_length=512)),
                ('host_format', models.IntegerField(choices=[(0, 'String'), (1, 'Regex')], default=0)),
                ('is_wildcard', models.BooleanField(default=False)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=512)),
                ('last_run_amass', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, 1))),
                ('last_run_securitytrails', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, 1))),
                ('derived_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbprograms.asset')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbprograms.team')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbprograms.team'),
        ),
        migrations.AddField(
            model_name='asset',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbprograms.team'),
        ),
    ]
