# Generated by Django 5.1.11 on 2025-06-26 13:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Hosts Added'), (2, 'Protobufs Added'), (3, 'WebAPIs Added'), (4, 'JS Changes'), (5, 'Git Monitor Changes'), (6, 'Status Code Change'), (7, 'S3 Misconfiguration'), (8, 'OAuth Resource Added'), (9, 'Nuclei Result'), (10, 'FFUF Result'), (11, 'Job Error'), (12, 'Direct Result'), (13, 'Buckets Added'), (14, 'OAuth Changes'), (15, 'Host Reachable'), (16, 'GraphQL Changes')], default=0)),
                ('title', models.CharField(max_length=255)),
                ('body', models.JSONField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quirk',
            fields=[
                ('notes', models.TextField(blank=True)),
                ('tag', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('reachable', models.BooleanField(null=True)),
                ('name_resolves', models.BooleanField(null=True)),
                ('last_resolved', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, 1))),
                ('is_alias', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('status_previous', models.IntegerField(default=0)),
                ('content_length', models.IntegerField(default=0)),
                ('in_scope', models.BooleanField(null=True)),
                ('alias_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', related_query_name='alias', to='pokebase.host')),
                ('quirks', models.ManyToManyField(blank=True, to='pokebase.quirk')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokebase.host')),
                ('quirks', models.ManyToManyField(blank=True, to='pokebase.quirk')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('record_type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'A'), (2, 'Aaaa'), (3, 'Cname'), (4, 'Ns'), (5, 'Txt'), (6, 'Ptr'), (7, 'Mx'), (8, 'Soa')], default=0)),
                ('value', models.TextField(blank=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokebase.host')),
                ('quirks', models.ManyToManyField(blank=True, to='pokebase.quirk')),
            ],
            options={
                'verbose_name_plural': 'DNS Record',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('quirks', models.ManyToManyField(blank=True, to='pokebase.quirk')),
            ],
            options={
                'verbose_name_plural': 'technologies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='host',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='pokebase.technology'),
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('quirks', models.ManyToManyField(blank=True, to='pokebase.quirk')),
            ],
            options={
                'verbose_name_plural': 'weaknesses',
            },
        ),
    ]
