# Generated by Django 5.1.11 on 2025-06-26 13:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bbprograms', '0001_initial'),
        ('pokebase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('provider', models.IntegerField(choices=[(0, 'AWS'), (1, 'GCP'), (2, 'Azure')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account_id', models.CharField(max_length=255, unique=True)),
                ('canonical_user_id', models.CharField(blank=True, help_text='obfuscated id for s3', max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=512)),
                ('use_for_ownership_check', models.BooleanField(default=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbprograms.team')),
            ],
            options={
                'ordering': ['account_id'],
            },
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('provider', models.IntegerField(choices=[(0, 'AWS'), (1, 'GCP'), (2, 'Azure')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('owner_from_acl', models.CharField(blank=True, max_length=512)),
                ('last_scanned', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, 1))),
                ('readable_object', models.CharField(blank=True, help_text='Used to help determine bucket owner', max_length=512)),
                ('exists', models.BooleanField(default=True)),
                ('ignore', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=False)),
                ('can_read_acl', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
                ('hosts', models.ManyToManyField(blank=True, to='pokebase.host')),
                ('quirks', models.ManyToManyField(blank=True, to='pokebase.quirk')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokecloud.cloudaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CloudKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('provider', models.IntegerField(choices=[(0, 'AWS'), (1, 'GCP'), (2, 'Azure')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key_id', models.CharField(max_length=255, unique=True)),
                ('valid', models.BooleanField(default=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokecloud.cloudaccount')),
                ('buckets', models.ManyToManyField(blank=True, to='pokecloud.bucket')),
                ('hosts', models.ManyToManyField(blank=True, to='pokebase.host')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_level', models.IntegerField(choices=[(0, 'Wip'), (1, 'Scanner'), (2, 'Confirmed')], default=2)),
                ('severity', models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=0)),
                ('description', models.TextField(blank=True)),
                ('reportid', models.IntegerField(blank=True, null=True)),
                ('fixed', models.BooleanField()),
                ('false_alarm', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokecloud.bucket')),
                ('weakness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pokebase.weakness')),
            ],
            options={
                'verbose_name_plural': 'vulnerabilities',
                'abstract': False,
            },
        ),
    ]
