# Generated by Django 5.1.11 on 2025-06-26 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokebase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255, unique=True)),
                ('secret', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('internal', models.BooleanField(default=False)),
                ('native', models.BooleanField(default=False)),
                ('client_service', models.CharField(blank=True, max_length=255)),
                ('app', models.CharField(blank=True, max_length=255)),
                ('product', models.CharField(blank=True, max_length=255)),
                ('redirect_url', models.CharField(blank=True, max_length=255)),
                ('full_metadata', models.TextField(blank=True)),
                ('client_credentials_metadata', models.TextField(blank=True)),
                ('quirks', models.ManyToManyField(blank=True, to='pokebase.quirk')),
            ],
            options={
                'verbose_name': 'OAuth Client',
                'ordering': ['client_id'],
            },
        ),
        migrations.CreateModel(
            name='OAuthResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('quirks', models.ManyToManyField(blank=True, to='pokebase.quirk')),
            ],
            options={
                'verbose_name': 'OAuth Resource',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OAuthPermissionsGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('grant_type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'authorization_code'), (2, 'client_credentials'), (3, 'device_auth'), (4, 'device_code'), (5, 'exchange_code'), (6, 'external_auth'), (7, 'password'), (8, 'token_to_token'), (9, 'bearer')], default=0)),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', related_query_name='grant', to='pokeoauth.oauthclient')),
                ('quirks', models.ManyToManyField(blank=True, to='pokebase.quirk')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', related_query_name='grant', to='pokeoauth.oauthresource')),
            ],
            options={
                'verbose_name': 'OAuth Permissions Grant',
                'ordering': ['resource__name'],
                'constraints': [models.UniqueConstraint(fields=('client', 'resource', 'grant_type'), name='unique_oauth_perm_grant')],
            },
        ),
    ]
