# Generated by Django 5.1.11 on 2025-06-26 13:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokebase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.IntegerField(choices=[(0, 'Unknown'), (2, 'Microservice'), (3, 'Site'), (4, 'Executable')], default=0, verbose_name='Type')),
                ('quirks', models.ManyToManyField(blank=True, to='pokebase.quirk')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('quirks', models.ManyToManyField(blank=True, to='pokebase.quirk')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('last_scanned_for_methods', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, 1))),
                ('last_scanned_for_templates', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, 1))),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.asset')),
                ('quirks', models.ManyToManyField(blank=True, to='pokebase.quirk')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.interface')),
                ('quirks', models.ManyToManyField(blank=True, to='pokebase.quirk')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=512)),
                ('action', models.CharField(blank=True, max_length=255)),
                ('http_method', models.IntegerField(choices=[(0, 'Unknown'), (1, 'GET'), (2, 'POST'), (3, 'DELETE'), (4, 'PUT'), (5, 'PATCH')], default=0, verbose_name='HTTP Method')),
                ('usable', models.BooleanField(null=True)),
                ('required_permission', models.CharField(blank=True, max_length=255)),
                ('response_message_type', models.CharField(blank=True, max_length=255)),
                ('last_scanned', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, 1))),
                ('scan_results', models.TextField(blank=True)),
                ('scan_usable', models.BooleanField(default=False)),
                ('scan_status', models.IntegerField(default=0)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.method')),
                ('quirks', models.ManyToManyField(blank=True, to='pokebase.quirk')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Path'), (2, 'Query'), (3, 'Cookie'), (4, 'Header'), (5, 'Body')], default=0)),
                ('value_encoding', models.IntegerField(choices=[(0, 'Unknown'), (1, 'URL'), (2, 'JSON'), (3, 'File'), (4, 'Base64'), (5, 'VDF')], default=0)),
                ('param_type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Int'), (2, 'String'), (3, 'Array'), (4, 'Message'), (5, 'Int32'), (6, 'Uint32'), (7, 'Int64'), (8, 'Uint64'), (9, 'Fixed64'), (10, 'Boolean'), (11, 'Rawbinary'), (12, 'Fixed32'), (13, 'Enum'), (14, 'Float')], default=0)),
                ('message_type', models.CharField(blank=True, max_length=255)),
                ('repeated', models.BooleanField(null=True)),
                ('required', models.BooleanField(null=True)),
                ('quirks', models.ManyToManyField(blank=True, to='pokebase.quirk')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.route')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_level', models.IntegerField(choices=[(0, 'Wip'), (1, 'Scanner'), (2, 'Confirmed')], default=2)),
                ('severity', models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=0)),
                ('description', models.TextField(blank=True)),
                ('reportid', models.IntegerField(blank=True, null=True)),
                ('fixed', models.BooleanField()),
                ('false_alarm', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.asset')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokebase.host')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.interface')),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.method')),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.parameter')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.route')),
                ('weakness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokebase.weakness')),
            ],
            options={
                'verbose_name_plural': 'vulnerabilities',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('protocol', models.IntegerField(choices=[(0, 'Unknown'), (1, 'HTTP'), (2, 'HTTPS')], default=2)),
                ('base_path', models.CharField(blank=True, max_length=512)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.asset')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokebase.host')),
                ('quirks', models.ManyToManyField(blank=True, to='pokebase.quirk')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.environment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset', 'protocol', 'host', 'base_path'), name='unique_deployment')],
            },
        ),
        migrations.AddConstraint(
            model_name='interface',
            constraint=models.UniqueConstraint(fields=('asset', 'name'), name='unique_interface'),
        ),
        migrations.AddConstraint(
            model_name='method',
            constraint=models.UniqueConstraint(fields=('interface', 'name'), name='unique_method'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('method', 'action', 'http_method', 'slug'), name='unique_route'),
        ),
        migrations.AddConstraint(
            model_name='parameter',
            constraint=models.UniqueConstraint(fields=('route', 'location', 'value_encoding', 'param_type', 'name'), name='unique_param'),
        ),
    ]
